more bug fixes
1. In debug mode (-v), function return values were sometimes mixed with debug output (terrible).
2. filterChainsWithPausedDest() didn't handle an empty chain ("") correctly.
3. Chains with paused destination VM incorrectly got closed when device changes happened inside a VM of their chain.

diff --git a/qcryptd b/qcryptd
--- a/qcryptd
+++ b/qcryptd
@@ -461,7 +461,8 @@ function logError {
 local msg="$1"
 local notify="${2:-1}"
 local summary="${3:-"$B_SCRIPT_NAME: ERROR"}"
-[ $DEBUG -eq 0 ] && echo "$SECONDS [$BASHPID] ERROR: $msg"
+#NOTE: we write to stderr (which is logged in debug mode) to avoid conflicts with echoed return values from inside functions
+[ $DEBUG -eq 0 ] && >&2 echo "$SECONDS [$BASHPID] ERROR: $msg"
 logger -p daemon.err -t "$B_SCRIPT_NAME" "[$BASHPID] $msg (target: $CONF_TARGET)"
 if [ $notify -eq 0 ] ; then
 	notify-send -u critical -t 60000 "$summary" "$msg" &
@@ -476,7 +477,8 @@ function logInfo {
 local msg="$1"
 local notify="${2:-1}"
 local summary="${3:-"$B_SCRIPT_NAME: INFO"}"
-[ $DEBUG -eq 0 ] && echo "$SECONDS [$BASHPID] INFO: $msg"
+#NOTE: we write to stderr (which is logged in debug mode) to avoid conflicts with echoed return values from inside functions
+[ $DEBUG -eq 0 ] && >&2 echo "$SECONDS [$BASHPID] INFO: $msg"
 logger -p daemon.notice -t "$B_SCRIPT_NAME" "[$BASHPID] $msg (target: $CONF_TARGET)"
 if [ $notify -eq 0 ] ; then
 	notify-send "$summary" "$msg" &
@@ -864,6 +866,7 @@ local list="$1"
 
 local chain=
 while IFS= read -r chain ; do
+	[ -z "$chain" ] && continue
 	local final="${CHAINS2INFO["${chain}_final destination vm"]}"
 	if isPaused "$final" ; then
 		[ $DEBUG -eq 0 ] && logInfo "$chain: The final destination VM $final appears to be paused. Ignoring."
@@ -894,10 +897,11 @@ if [ $shutdown -eq 0 ] ; then
 elif [ $paused -eq 0 ] ; then
 	#special case: do not consider the chain broken, if the final destination VM is paused
 	#reason: it'll fail, but in fact qcryptd should be alright once the user unpauses the VM --> unclear state --> do nothing now and check again on unpause
-	#for paused intermediate VMs we still error out as that may cause data loss otherwise
+	#for paused intermediate VMs we still error out (unless their dest is paused) as that may cause data loss otherwise
 	chains="$(filterChainsWithPausedDest "${VMS2CHAINS["$vm"]}")"
 else
-	chains="$(getBadChains "${VMS2CHAINS["$vm"]}")"
+	chains="$(filterChainsWithPausedDest "${VMS2CHAINS["$vm"]}")" #see above
+	chains="$(getBadChains "$chains")"
 fi
 
 [ $DEBUG -eq 0 ] && logInfo "Chains about to be closed (if active):"$'\n'"$chains"$'\n'
